name: Build the QGIS plugin (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]
        c_compiler: [clang, gcc]
        build_config: [ 
          {qgis_version: 3_10_4, release: rel, os: ubuntu-24.04},
          {qgis_version: 3_44_4, release: ltr, os: ubuntu-24.04},
        ]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    runs-on: ${{ matrix.build_config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install qtbase5-dev qt5-qmake cmake nlohmann-json3-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DQGIS_PREFIX_PATH=dependencies/qgis/linux_x86_64/${{ matrix.build_config.release }}/${{ matrix.build_config.qgis_version }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -S ${{ github.workspace }}
        -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - uses: actions/upload-artifact@v4
      with:
        name: qgis-${{ matrix.build_config.release }}-${{ matrix.build_config.qgis_version }}-plugin-linux-${{ matrix.c_compiler }}-${{ matrix.build_type }}
        path: ${{ github.workspace }}/**/libhelloworldplugin.so