name: Build the Plugin Dependencies (Windows)

on:
  workflow_dispatch:
    inputs:
      qgis-version:
        description: "The QGIS version to build the dependencies."
        default: '3_36_3'
      lib-version:
        description: "The QGIS version as a different string."
        default: '3.36'
      build-timestamp:
        description: "The QGIS build timestamp (you can find it here: `https://download.qgis.org/downloads/macos/pr/`)."
        default: '20240517_122510'
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: qgis/QGIS
          ref: final-${{ inputs.qgis-version || '3_36_3' }}

      - name: Install core & build dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: base-devel
          pacboy: >-
            draco:p exiv2:p gdal:p gsl:p hdf5:p libxml2:p libzip:p netcdf:p opencl-icd:p pdal:p
            protobuf:p proj:p qca-qt5:p qscintilla-qt5:p qt5-3d:p qt5-base:p qt5-declarative:p
            qt5-gamepad:p qt5-location:p qt5-serialport:p qt5-svg:p qtkeychain-qt5:p qtwebkit:p
            qwt-qt5:p spatialindex:p cc:p cmake:p ninja:p opencl-clhpp:p qt5-tools:p python:p ccache:p
            python-gdal:p python-owslib:p python-pyqt5:p python-qscintilla-qt5:p pyqt-builder:p sip:p
          update: true
          release: false

      - name: Configure QGIS
        run: |
          cmake \
            -G"Ninja" \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DPython_EXECUTABLE=${MINGW_PREFIX}/bin/python \
            -DWITH_3D=ON \
            -DWITH_DRACO=ON \
            -DWITH_PDAL=ON \
            -DWITH_CUSTOM_WIDGETS=ON \
            -DWITH_BINDINGS=ON \
            -DWITH_GRASS=OFF \
            -DUSE_CCACHE=ON \
            -S . \
            -B build

      - name: Build QGIS
        run: |
          cmake --build build
          ccache -s