name: Build the QGIS plugin (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]
        c_compiler: [clang, gcc]
        qgis_version: [3_10_4]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install qgis-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
	      -DQGIS_BUILD_PATH=dependencies/qgis/linux_x86_64/${{ matrix.qgis_version }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - uses: actions/upload-artifact@v4
      with:
        name: qgis-${{ matrix.qgis_version }}-plugin-windows-linux-${{ matrix.c_compiler }}-${{ matrix.build_type }}
        path: ${{ github.workspace }}/**/libhelloworldplugin.so