name: Build the QGIS plugin (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]
        c_compiler: [clang, gcc]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install qgis-dev

    # Workaround for incompatible clang and libstc++ versions, see
    # <https://github.com/actions/runner-images/issues/8659> for more info.
    # The basic idea here is to remove g++ 13 and its C++ standard library
    # and replace that with a compatible version of libstdc++.
    - name: Workaround for GHA runner images issue 8659
      run: |
        sudo apt-get purge -y g++-13 gcc-13 libstdc++-13-dev
        sudo apt-get install -y --allow-downgrades libstdc++-12-dev libstdc++6=12.* libgcc-s1=12.*

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - uses: actions/upload-artifact@v3
      with:
        name: qgis-plugin-windows-linux-${{ matrix.c_compiler }}-${{ matrix.build_type }}
        path: ${{ github.workspace }}/**/libhelloworldplugin.so