name: Build the Plugin Dependencies (macOS)

on:
  workflow_dispatch:
    inputs:
      qgis-version:
        description: "The QGIS version to build the dependencies."
        default: '3_34_2'
      build-timestamp:
        description: "The QGIS build timestamp."
        default: '20231222_122631'
        

env:
  QT_VERSION: 5.15.2
  QGIS_DEPS_VERSION: 0.9
  QGIS_DEPS_PATCH_VERSION: 0
  BUILD_DIR: build-QGIS

jobs:
  build-macos-dependencies:
    runs-on: macos-latest

    steps:
    - name: Download the Official QGIS Release
      # use a wildcard for the build date, as the build date is not known
      run: |
        wget -O qgis_installer.dmg https://download.qgis.org/downloads/macos/pr/qgis_pr_final-${{ inputs.qgis-version }}_${{ inputs.build-timestamp }}.dmg

      # wget -O qgis_installer.dmg -r --no-parent -A 'qgis_pr_final-${{ inputs.qgis-version }}_*.dmg' https://download.qgis.org/downloads/macos/pr/

    - name: Install Official QGIS
      run: |
        hdiutil attach qgis_installer.dmg
        echo QGIS installer image mounted.
        ls -la
        cd /Volumes/QGIS/
        ls -la
        echo Install QGIS package
        sudo installer -pkg QGIS.pkg -target "/"
        hdiutil detach /Volumes/QGIS/

    - uses: actions/checkout@v4
      with:
        repository: qgis/QGIS
        ref: final-${{ inputs.qgis-version }}

    - name: Download Qt
      run: |
        wget https://qgis.org/downloads/macos/deps/qt-${QT_VERSION}.tar.gz
 
    - name: Download qgis-deps
      run: |
        wget https://qgis.org/downloads/macos/deps/qgis-deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.tar.gz

    - name: Install Qt and deps
      run: |
        wget https://qgis.org/downloads/macos/deps/install_qgis_deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.bash
        chmod +x ./install_qgis_deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.bash
        echo ::group::Install deps
        sudo ./install_qgis_deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.bash
      
    - name: Run cmake
      run: |
        mkdir -p ${BUILD_DIR}
        cd ${BUILD_DIR}

        PATH=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/bin:$PATH \
        cmake -DQGIS_MAC_DEPS_DIR=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage \
              -DCMAKE_PREFIX_PATH=/opt/Qt/${QT_VERSION}/clang_64 \
              -DWITH_BINDINGS=TRUE \
              -DWITH_3D=TRUE \
              -DWITH_DRACO=FALSE \
              -DWITH_PDAL=TRUE \
              -DWITH_EPT=TRUE \
              ..

    - name: Build QGIS
      run: |
        cd ${BUILD_DIR}
        make -j $(sysctl -n hw.ncpu)