name: Build the Plugin Dependencies (macOS)
# This action is used to generate the plugin dependencies
# for macOS targets. A C++ plugin for QGIS needs to link the
# static QGIS libraries (e.g. qgis_core). Pre-built libraries
# are available in the QGIS installations, but they do not come
# with the accompanying header files. If you try to rebuild the
# libraries from scratch (e.g. by checking out the right commit
# and building QGIS), the C++ plugin will compile, but you won't
# be able to use it, due to the one-definition rule. QGIS
# will crash when trying to run with a C++ plugin on macOS.
# This GitHub action solves this issue by:
# 1) rebuilding the right QGIS version to get the header files.
# 2) downloading the QGIS installation binary to get the library
#    files.
# 3) uploading the header + libraries as artifacts.
on:
  workflow_dispatch:
    inputs:
      qgis-version:
        description: "The QGIS version to build the dependencies."
        default: '3_34_2'
      build-timestamp:
        description: "The QGIS build timestamp."
        default: '20231222_122631'
        

env:
  QT_VERSION: 5.15.2
  QGIS_DEPS_VERSION: 0.9
  QGIS_DEPS_PATCH_VERSION: 0
  BUILD_DIR: build-QGIS
  OUT_DIR: macos-final-libraries

jobs:
  build-macos-dependencies:
    runs-on: macos-latest

    steps:
    - name: Download the Official QGIS Release
      # use a wildcard for the build date, as the build date is not known
      run: |
        wget -O qgis_installer.dmg https://download.qgis.org/downloads/macos/pr/qgis_pr_final-${{ inputs.qgis-version }}_${{ inputs.build-timestamp }}.dmg

      # wget -O qgis_installer.dmg -r --no-parent -A 'qgis_pr_final-${{ inputs.qgis-version }}_*.dmg' https://download.qgis.org/downloads/macos/pr/

    - name: Mount Official QGIS
      # To bypass EULA, we convert to cdr format.
      run: |
        hdiutil convert qgis_installer.dmg -format UDTO -o qgis_installer.cdr
        hdiutil attach -quiet -nobrowse -noverify -noautoopen qgis_installer.cdr
        echo QGIS installer image mounted.
        
    - name: Copy pre-built libraries
      run: |
        mkdir -p ${{ env.OUT_DIR }}
        cp -v -R /Volumes/QGIS.app/QGIS.app/Contents/Frameworks/qgis_3d.framework ${{ env.OUT_DIR }}
        cp -R /Volumes/QGIS.app/QGIS.app/Contents/Frameworks/qgis_analysis.framework ${{ env.OUT_DIR }}
        cp -R /Volumes/QGIS.app/QGIS.app/Contents/Frameworks/qgis_core.framework ${{ env.OUT_DIR }}
        cp -R /Volumes/QGIS.app/QGIS.app/Contents/Frameworks/qgis_gui.framework ${{ env.OUT_DIR }}
        cp -R /Volumes/QGIS.app/QGIS.app/Contents/Frameworks/qgis_native.framework ${{ env.OUT_DIR }}
        cd ${{ env.OUT_DIR }}
        ls -la

    - name: Unmount official QGIS
      run: |
        hdiutil detach /Volumes/QGIS.app/

    - uses: actions/checkout@v4
      with:
        repository: qgis/QGIS
        ref: final-${{ inputs.qgis-version }}

    - name: Download Qt
      run: |
        wget https://qgis.org/downloads/macos/deps/qt-${QT_VERSION}.tar.gz
 
    - name: Download qgis-deps
      run: |
        wget https://qgis.org/downloads/macos/deps/qgis-deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.tar.gz

    - name: Install Qt and deps
      run: |
        wget https://qgis.org/downloads/macos/deps/install_qgis_deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.bash
        chmod +x ./install_qgis_deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.bash
        echo ::group::Install deps
        sudo ./install_qgis_deps-${QGIS_DEPS_VERSION}.${QGIS_DEPS_PATCH_VERSION}.bash
      
    - name: Run cmake
      run: |
        mkdir -p ${BUILD_DIR}
        cd ${BUILD_DIR}

        PATH=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/bin:$PATH \
        cmake -DQGIS_MAC_DEPS_DIR=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage \
              -DCMAKE_PREFIX_PATH=/opt/Qt/${QT_VERSION}/clang_64 \
              -DWITH_BINDINGS=TRUE \
              -DWITH_3D=TRUE \
              -DWITH_DRACO=FALSE \
              -DWITH_PDAL=TRUE \
              -DWITH_EPT=TRUE \
              ..

    - name: Build QGIS
      run: |
        cd ${BUILD_DIR}
        make -j $(sysctl -n hw.ncpu)
            
    - name: Copy the built headers to the already existing libraries
      run: |
        cp -v -R ${BUILD_DIR}/output/lib/qgis_3d.framework/Headers ${{ env.OUT_DIR }}/qgis_3d.framework
        cp -v -R ${BUILD_DIR}/output/lib/qgis_analysis.framework/Headers ${{ env.OUT_DIR }}/qgis_analysis.framework
        cp -v -R ${BUILD_DIR}/output/lib/qgis_core.framework/Headers ${{ env.OUT_DIR }}/qgis_core.framework
        cp -v -R ${BUILD_DIR}/output/lib/qgis_gui.framework/Headers ${{ env.OUT_DIR }}/qgis_gui.framework
        cp -v -R ${BUILD_DIR}/output/lib/qgis_native.framework/Headers ${{ env.OUT_DIR }}/qgis_native.framework

    - uses: actions/upload-artifact@v4
      with:
        name: qgis-macos-libraries-${{ inputs.qgis-version }}_${{ inputs.build-timestamp }}
        path: ${{ env.OUT_DIR }}